name: CI

on:
  push:
    branches: [ dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'

      - name: Install, test and build
        run: |
          npm install
          npm test
          npm run build
          echo "NPM Done"
          
      - name: build image docker
        id: docker_build
        run: |
          docker build -t xebxke/cactus:${BRANCH#refs/heads/}-$COMMIT .
          echo "Docker builded"
          
      - name: Done
        run: echo "Done!"
